# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_generalizer.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_generalizer(object):
    def setupUi(self, generalizer):
        generalizer.setObjectName("generalizer")
        generalizer.resize(493, 348)
        self.gridLayout_20 = QtWidgets.QGridLayout(generalizer)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.cbBatch = QtWidgets.QCheckBox(generalizer)
        self.cbBatch.setObjectName("cbBatch")
        self.gridLayout_20.addWidget(self.cbBatch, 0, 0, 1, 1)
        self.bHelp = QtWidgets.QPushButton(generalizer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bHelp.sizePolicy().hasHeightForWidth())
        self.bHelp.setSizePolicy(sizePolicy)
        self.bHelp.setFlat(True)
        self.bHelp.setObjectName("bHelp")
        self.gridLayout_20.addWidget(self.bHelp, 0, 2, 1, 1)
        self.bOk = QtWidgets.QPushButton(generalizer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bOk.sizePolicy().hasHeightForWidth())
        self.bOk.setSizePolicy(sizePolicy)
        self.bOk.setObjectName("bOk")
        self.gridLayout_20.addWidget(self.bOk, 2, 1, 1, 1)
        self.bCancel = QtWidgets.QPushButton(generalizer)
        self.bCancel.setObjectName("bCancel")
        self.gridLayout_20.addWidget(self.bCancel, 2, 2, 1, 1)
        self.stackBatch = QtWidgets.QStackedWidget(generalizer)
        self.stackBatch.setObjectName("stackBatch")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label = QtWidgets.QLabel(self.page_6)
        self.label.setObjectName("label")
        self.gridLayout_19.addWidget(self.label, 0, 0, 1, 1)
        self.cbInput = QtWidgets.QComboBox(self.page_6)
        self.cbInput.setObjectName("cbInput")
        self.gridLayout_19.addWidget(self.cbInput, 1, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.page_6)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.cbAlgorithm = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbAlgorithm.sizePolicy().hasHeightForWidth())
        self.cbAlgorithm.setSizePolicy(sizePolicy)
        self.cbAlgorithm.setObjectName("cbAlgorithm")
        self.cbAlgorithm.addItem("")
        self.cbAlgorithm.addItem("")
        self.cbAlgorithm.addItem("")
        self.cbAlgorithm.addItem("")
        self.cbAlgorithm.addItem("")
        self.cbAlgorithm.addItem("")
        self.cbAlgorithm.addItem("")
        self.cbAlgorithm.addItem("")
        self.cbAlgorithm.addItem("")
        self.cbAlgorithm.addItem("")
        self.cbAlgorithm.addItem("")
        self.cbAlgorithm.addItem("")
        self.cbAlgorithm.addItem("")
        self.cbAlgorithm.addItem("")
        self.cbAlgorithm.addItem("")
        self.gridLayout_2.addWidget(self.cbAlgorithm, 0, 1, 1, 1)
        self.stackOptions = QtWidgets.QStackedWidget(self.groupBox)
        self.stackOptions.setObjectName("stackOptions")
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_11)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_12 = QtWidgets.QLabel(self.page_11)
        self.label_12.setObjectName("label_12")
        self.gridLayout_11.addWidget(self.label_12, 0, 0, 1, 1)
        self.sbRemove_thresh = QtWidgets.QDoubleSpinBox(self.page_11)
        self.sbRemove_thresh.setDecimals(4)
        self.sbRemove_thresh.setMinimum(0.0001)
        self.sbRemove_thresh.setMaximum(9999999.9999)
        self.sbRemove_thresh.setProperty("value", 0.0001)
        self.sbRemove_thresh.setObjectName("sbRemove_thresh")
        self.gridLayout_11.addWidget(self.sbRemove_thresh, 0, 1, 1, 1)
        self.stackOptions.addWidget(self.page_11)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page_12)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_18 = QtWidgets.QLabel(self.page_12)
        self.label_18.setObjectName("label_18")
        self.gridLayout_12.addWidget(self.label_18, 0, 0, 1, 1)
        self.sbDP_thresh = QtWidgets.QDoubleSpinBox(self.page_12)
        self.sbDP_thresh.setDecimals(4)
        self.sbDP_thresh.setMinimum(0.0001)
        self.sbDP_thresh.setMaximum(9999999.9999)
        self.sbDP_thresh.setProperty("value", 0.0001)
        self.sbDP_thresh.setObjectName("sbDP_thresh")
        self.gridLayout_12.addWidget(self.sbDP_thresh, 0, 1, 1, 1)
        self.stackOptions.addWidget(self.page_12)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.sbJenks_thresh = QtWidgets.QDoubleSpinBox(self.page_2)
        self.sbJenks_thresh.setDecimals(4)
        self.sbJenks_thresh.setMaximum(9999999.9999)
        self.sbJenks_thresh.setProperty("value", 0.0001)
        self.sbJenks_thresh.setObjectName("sbJenks_thresh")
        self.gridLayout_4.addWidget(self.sbJenks_thresh, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.sbJenks_angle = QtWidgets.QDoubleSpinBox(self.page_2)
        self.sbJenks_angle.setMaximum(180.0)
        self.sbJenks_angle.setProperty("value", 3.0)
        self.sbJenks_angle.setObjectName("sbJenks_angle")
        self.gridLayout_4.addWidget(self.sbJenks_angle, 1, 1, 1, 1)
        self.stackOptions.addWidget(self.page_2)
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_13)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(self.page_13)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.sbLang_thresh = QtWidgets.QDoubleSpinBox(self.page_13)
        self.sbLang_thresh.setDecimals(4)
        self.sbLang_thresh.setMinimum(0.0001)
        self.sbLang_thresh.setMaximum(9999999.9999)
        self.sbLang_thresh.setProperty("value", 0.0001)
        self.sbLang_thresh.setObjectName("sbLang_thresh")
        self.gridLayout_3.addWidget(self.sbLang_thresh, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.page_13)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 0, 1, 1)
        self.sbLang_LA = QtWidgets.QSpinBox(self.page_13)
        self.sbLang_LA.setMinimum(1)
        self.sbLang_LA.setMaximum(9999)
        self.sbLang_LA.setProperty("value", 8)
        self.sbLang_LA.setObjectName("sbLang_LA")
        self.gridLayout_3.addWidget(self.sbLang_LA, 1, 1, 1, 1)
        self.stackOptions.addWidget(self.page_13)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_11 = QtWidgets.QLabel(self.page_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 0, 0, 1, 1)
        self.sbRW_thresh = QtWidgets.QDoubleSpinBox(self.page_4)
        self.sbRW_thresh.setDecimals(4)
        self.sbRW_thresh.setMaximum(9999999.9999)
        self.sbRW_thresh.setProperty("value", 0.0001)
        self.sbRW_thresh.setObjectName("sbRW_thresh")
        self.gridLayout_6.addWidget(self.sbRW_thresh, 0, 1, 1, 1)
        self.stackOptions.addWidget(self.page_4)
        self.page_14 = QtWidgets.QWidget()
        self.page_14.setObjectName("page_14")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_14)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_20 = QtWidgets.QLabel(self.page_14)
        self.label_20.setObjectName("label_20")
        self.gridLayout_14.addWidget(self.label_20, 0, 0, 1, 1)
        self.sbReduction_thresh = QtWidgets.QDoubleSpinBox(self.page_14)
        self.sbReduction_thresh.setDecimals(4)
        self.sbReduction_thresh.setMinimum(0.0001)
        self.sbReduction_thresh.setMaximum(9999999.9999)
        self.sbReduction_thresh.setObjectName("sbReduction_thresh")
        self.gridLayout_14.addWidget(self.sbReduction_thresh, 0, 1, 1, 1)
        self.stackOptions.addWidget(self.page_14)
        self.page_15 = QtWidgets.QWidget()
        self.page_15.setObjectName("page_15")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.page_15)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_21 = QtWidgets.QLabel(self.page_15)
        self.label_21.setObjectName("label_21")
        self.gridLayout_15.addWidget(self.label_21, 0, 0, 1, 1)
        self.sbBoyle_LA = QtWidgets.QSpinBox(self.page_15)
        self.sbBoyle_LA.setMinimum(2)
        self.sbBoyle_LA.setMaximum(999)
        self.sbBoyle_LA.setProperty("value", 7)
        self.sbBoyle_LA.setObjectName("sbBoyle_LA")
        self.gridLayout_15.addWidget(self.sbBoyle_LA, 0, 1, 1, 1)
        self.stackOptions.addWidget(self.page_15)
        self.page_16 = QtWidgets.QWidget()
        self.page_16.setObjectName("page_16")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.page_16)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_22 = QtWidgets.QLabel(self.page_16)
        self.label_22.setObjectName("label_22")
        self.gridLayout_16.addWidget(self.label_22, 0, 0, 1, 1)
        self.sbChaiken_level = QtWidgets.QSpinBox(self.page_16)
        self.sbChaiken_level.setMinimum(1)
        self.sbChaiken_level.setMaximum(99)
        self.sbChaiken_level.setObjectName("sbChaiken_level")
        self.gridLayout_16.addWidget(self.sbChaiken_level, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.page_16)
        self.label_23.setObjectName("label_23")
        self.gridLayout_16.addWidget(self.label_23, 1, 0, 1, 1)
        self.sbChaiken_weight = QtWidgets.QDoubleSpinBox(self.page_16)
        self.sbChaiken_weight.setMinimum(1.0)
        self.sbChaiken_weight.setProperty("value", 3.0)
        self.sbChaiken_weight.setObjectName("sbChaiken_weight")
        self.gridLayout_16.addWidget(self.sbChaiken_weight, 1, 1, 1, 1)
        self.stackOptions.addWidget(self.page_16)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.sbHermite_tightness = QtWidgets.QDoubleSpinBox(self.page)
        self.sbHermite_tightness.setProperty("value", 0.5)
        self.sbHermite_tightness.setObjectName("sbHermite_tightness")
        self.gridLayout.addWidget(self.sbHermite_tightness, 1, 1, 1, 1)
        self.sbHermite_steps = QtWidgets.QDoubleSpinBox(self.page)
        self.sbHermite_steps.setDecimals(4)
        self.sbHermite_steps.setMaximum(9999999.9999)
        self.sbHermite_steps.setProperty("value", 0.0001)
        self.sbHermite_steps.setObjectName("sbHermite_steps")
        self.gridLayout.addWidget(self.sbHermite_steps, 0, 1, 1, 1)
        self.stackOptions.addWidget(self.page)
        self.page_17 = QtWidgets.QWidget()
        self.page_17.setObjectName("page_17")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.page_17)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_24 = QtWidgets.QLabel(self.page_17)
        self.label_24.setObjectName("label_24")
        self.gridLayout_17.addWidget(self.label_24, 0, 0, 1, 1)
        self.sbDist_slide = QtWidgets.QDoubleSpinBox(self.page_17)
        self.sbDist_slide.setSingleStep(0.1)
        self.sbDist_slide.setProperty("value", 0.5)
        self.sbDist_slide.setObjectName("sbDist_slide")
        self.gridLayout_17.addWidget(self.sbDist_slide, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.page_17)
        self.label_25.setObjectName("label_25")
        self.gridLayout_17.addWidget(self.label_25, 1, 0, 1, 1)
        self.sbDist_LA = QtWidgets.QSpinBox(self.page_17)
        self.sbDist_LA.setMinimum(3)
        self.sbDist_LA.setMaximum(999)
        self.sbDist_LA.setSingleStep(2)
        self.sbDist_LA.setProperty("value", 7)
        self.sbDist_LA.setObjectName("sbDist_LA")
        self.gridLayout_17.addWidget(self.sbDist_LA, 1, 1, 1, 1)
        self.stackOptions.addWidget(self.page_17)
        self.page_18 = QtWidgets.QWidget()
        self.page_18.setObjectName("page_18")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.page_18)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_26 = QtWidgets.QLabel(self.page_18)
        self.label_26.setObjectName("label_26")
        self.gridLayout_18.addWidget(self.label_26, 0, 0, 1, 1)
        self.sbSlide_slide = QtWidgets.QDoubleSpinBox(self.page_18)
        self.sbSlide_slide.setSingleStep(0.1)
        self.sbSlide_slide.setProperty("value", 0.5)
        self.sbSlide_slide.setObjectName("sbSlide_slide")
        self.gridLayout_18.addWidget(self.sbSlide_slide, 0, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.page_18)
        self.label_27.setObjectName("label_27")
        self.gridLayout_18.addWidget(self.label_27, 1, 0, 1, 1)
        self.sbSlide_LA = QtWidgets.QSpinBox(self.page_18)
        self.sbSlide_LA.setMinimum(3)
        self.sbSlide_LA.setMaximum(999)
        self.sbSlide_LA.setSingleStep(2)
        self.sbSlide_LA.setProperty("value", 7)
        self.sbSlide_LA.setObjectName("sbSlide_LA")
        self.gridLayout_18.addWidget(self.sbSlide_LA, 1, 1, 1, 1)
        self.stackOptions.addWidget(self.page_18)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.sbSnakes_alpha = QtWidgets.QDoubleSpinBox(self.page_3)
        self.sbSnakes_alpha.setMaximum(9999.99)
        self.sbSnakes_alpha.setProperty("value", 1.0)
        self.sbSnakes_alpha.setObjectName("sbSnakes_alpha")
        self.gridLayout_5.addWidget(self.sbSnakes_alpha, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.sbSnakes_beta = QtWidgets.QDoubleSpinBox(self.page_3)
        self.sbSnakes_beta.setMaximum(9999.99)
        self.sbSnakes_beta.setProperty("value", 0.5)
        self.sbSnakes_beta.setObjectName("sbSnakes_beta")
        self.gridLayout_5.addWidget(self.sbSnakes_beta, 1, 1, 1, 1)
        self.stackOptions.addWidget(self.page_3)
        self.gridLayout_2.addWidget(self.stackOptions, 1, 0, 1, 2)
        self.gridLayout_19.addWidget(self.groupBox, 2, 0, 1, 2)
        self.eOutput = QtWidgets.QLineEdit(self.page_6)
        self.eOutput.setEnabled(False)
        self.eOutput.setObjectName("eOutput")
        self.gridLayout_19.addWidget(self.eOutput, 4, 0, 1, 1)
        self.bBrowse = QtWidgets.QPushButton(self.page_6)
        self.bBrowse.setEnabled(False)
        self.bBrowse.setObjectName("bBrowse")
        self.gridLayout_19.addWidget(self.bBrowse, 4, 1, 1, 1)
        self.cbOutFile = QtWidgets.QCheckBox(self.page_6)
        self.cbOutFile.setObjectName("cbOutFile")
        self.gridLayout_19.addWidget(self.cbOutFile, 3, 0, 1, 1)
        self.stackBatch.addWidget(self.page_6)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.page_10)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.lstLayers = QtWidgets.QListWidget(self.page_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstLayers.sizePolicy().hasHeightForWidth())
        self.lstLayers.setSizePolicy(sizePolicy)
        self.lstLayers.setObjectName("lstLayers")
        self.gridLayout_21.addWidget(self.lstLayers, 1, 0, 1, 1)
        self.tblBatchAlg = QtWidgets.QTableWidget(self.page_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblBatchAlg.sizePolicy().hasHeightForWidth())
        self.tblBatchAlg.setSizePolicy(sizePolicy)
        self.tblBatchAlg.setObjectName("tblBatchAlg")
        self.tblBatchAlg.setColumnCount(3)
        self.tblBatchAlg.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblBatchAlg.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblBatchAlg.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblBatchAlg.setHorizontalHeaderItem(2, item)
        self.gridLayout_21.addWidget(self.tblBatchAlg, 3, 0, 3, 1)
        self.bAddAlg = QtWidgets.QPushButton(self.page_10)
        self.bAddAlg.setObjectName("bAddAlg")
        self.gridLayout_21.addWidget(self.bAddAlg, 3, 1, 1, 1)
        self.bDelAlg = QtWidgets.QPushButton(self.page_10)
        self.bDelAlg.setObjectName("bDelAlg")
        self.gridLayout_21.addWidget(self.bDelAlg, 4, 1, 1, 1)
        self.bEditAlg = QtWidgets.QPushButton(self.page_10)
        self.bEditAlg.setObjectName("bEditAlg")
        self.gridLayout_21.addWidget(self.bEditAlg, 5, 1, 1, 1)
        self.eDir = QtWidgets.QLineEdit(self.page_10)
        self.eDir.setEnabled(False)
        self.eDir.setObjectName("eDir")
        self.gridLayout_21.addWidget(self.eDir, 7, 0, 1, 1)
        self.bBrowseDir = QtWidgets.QPushButton(self.page_10)
        self.bBrowseDir.setEnabled(False)
        self.bBrowseDir.setObjectName("bBrowseDir")
        self.gridLayout_21.addWidget(self.bBrowseDir, 7, 1, 1, 1)
        self.cbOutDir = QtWidgets.QCheckBox(self.page_10)
        self.cbOutDir.setObjectName("cbOutDir")
        self.gridLayout_21.addWidget(self.cbOutDir, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page_10)
        self.label_5.setObjectName("label_5")
        self.gridLayout_21.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page_10)
        self.label_6.setObjectName("label_6")
        self.gridLayout_21.addWidget(self.label_6, 0, 0, 1, 1)
        self.stackBatch.addWidget(self.page_10)
        self.gridLayout_20.addWidget(self.stackBatch, 1, 0, 1, 3)
        self.label.setBuddy(self.cbInput)
        self.label_12.setBuddy(self.sbRemove_thresh)

        self.retranslateUi(generalizer)
        self.stackBatch.setCurrentIndex(0)
        self.cbAlgorithm.setCurrentIndex(1)
        self.stackOptions.setCurrentIndex(0)
        self.bCancel.clicked.connect(generalizer.close)
        QtCore.QMetaObject.connectSlotsByName(generalizer)
        generalizer.setTabOrder(self.cbBatch, self.cbInput)
        generalizer.setTabOrder(self.cbInput, self.cbAlgorithm)
        generalizer.setTabOrder(self.cbAlgorithm, self.sbRemove_thresh)
        generalizer.setTabOrder(self.sbRemove_thresh, self.cbOutFile)
        generalizer.setTabOrder(self.cbOutFile, self.eOutput)
        generalizer.setTabOrder(self.eOutput, self.bBrowse)
        generalizer.setTabOrder(self.bBrowse, self.bOk)
        generalizer.setTabOrder(self.bOk, self.bCancel)
        generalizer.setTabOrder(self.bCancel, self.sbLang_LA)
        generalizer.setTabOrder(self.sbLang_LA, self.sbReduction_thresh)
        generalizer.setTabOrder(self.sbReduction_thresh, self.sbBoyle_LA)
        generalizer.setTabOrder(self.sbBoyle_LA, self.sbChaiken_level)
        generalizer.setTabOrder(self.sbChaiken_level, self.sbChaiken_weight)
        generalizer.setTabOrder(self.sbChaiken_weight, self.sbHermite_steps)
        generalizer.setTabOrder(self.sbHermite_steps, self.sbHermite_tightness)
        generalizer.setTabOrder(self.sbHermite_tightness, self.sbDist_slide)
        generalizer.setTabOrder(self.sbDist_slide, self.sbDist_LA)
        generalizer.setTabOrder(self.sbDist_LA, self.sbSlide_slide)
        generalizer.setTabOrder(self.sbSlide_slide, self.sbSlide_LA)
        generalizer.setTabOrder(self.sbSlide_LA, self.bHelp)
        generalizer.setTabOrder(self.bHelp, self.sbLang_thresh)
        generalizer.setTabOrder(self.sbLang_thresh, self.sbDP_thresh)
        generalizer.setTabOrder(self.sbDP_thresh, self.lstLayers)
        generalizer.setTabOrder(self.lstLayers, self.tblBatchAlg)
        generalizer.setTabOrder(self.tblBatchAlg, self.bAddAlg)
        generalizer.setTabOrder(self.bAddAlg, self.bDelAlg)
        generalizer.setTabOrder(self.bDelAlg, self.bEditAlg)
        generalizer.setTabOrder(self.bEditAlg, self.eDir)
        generalizer.setTabOrder(self.eDir, self.bBrowseDir)
        generalizer.setTabOrder(self.bBrowseDir, self.cbOutDir)

    def retranslateUi(self, generalizer):
        _translate = QtCore.QCoreApplication.translate
        generalizer.setWindowTitle(_translate("generalizer", "Generalizer"))
        self.cbBatch.setText(_translate("generalizer", "Batch mode"))
        self.bHelp.setText(_translate("generalizer", "?"))
        self.bOk.setText(_translate("generalizer", "OK"))
        self.bCancel.setText(_translate("generalizer", "Close"))
        self.label.setText(_translate("generalizer", "Input line layer:"))
        self.groupBox.setTitle(_translate("generalizer", "Options"))
        self.label_3.setText(_translate("generalizer", "Alghoritm:"))
        self.cbAlgorithm.setItemText(0, _translate("generalizer", "-----Generalizing-----"))
        self.cbAlgorithm.setItemText(1, _translate("generalizer", "Remove small objects"))
        self.cbAlgorithm.setItemText(2, _translate("generalizer", "-----Simplifying-----"))
        self.cbAlgorithm.setItemText(3, _translate("generalizer", "Douglas-Peucker Algorithm"))
        self.cbAlgorithm.setItemText(4, _translate("generalizer", "Jenk\'s Algorithm"))
        self.cbAlgorithm.setItemText(5, _translate("generalizer", "Lang Algorithm"))
        self.cbAlgorithm.setItemText(6, _translate("generalizer", "Reumann-Witkam Algorithm"))
        self.cbAlgorithm.setItemText(7, _translate("generalizer", "Vertex Reduction"))
        self.cbAlgorithm.setItemText(8, _translate("generalizer", "-----Smoothing-----"))
        self.cbAlgorithm.setItemText(9, _translate("generalizer", "Boyle\'s Forward-Looking Algorithm"))
        self.cbAlgorithm.setItemText(10, _translate("generalizer", "Chaiken\'s Algorithm"))
        self.cbAlgorithm.setItemText(11, _translate("generalizer", "Hermite Spline Interpolation"))
        self.cbAlgorithm.setItemText(12, _translate("generalizer", "McMaster\'s Distance-Weighting Algorithm"))
        self.cbAlgorithm.setItemText(13, _translate("generalizer", "McMaster\'s Sliding Averaging Algorithm"))
        self.cbAlgorithm.setItemText(14, _translate("generalizer", "Snakes Algorithm"))
        self.label_12.setText(_translate("generalizer", "Threshold:"))
        self.label_18.setText(_translate("generalizer", "Threshold:"))
        self.label_7.setText(_translate("generalizer", "Threshold:"))
        self.label_8.setText(_translate("generalizer", "Angle threshold:"))
        self.label_13.setText(_translate("generalizer", "Threshold:"))
        self.label_19.setText(_translate("generalizer", "Looka ahead:"))
        self.label_11.setText(_translate("generalizer", "Threshold:"))
        self.label_20.setText(_translate("generalizer", "Threshold:"))
        self.label_21.setText(_translate("generalizer", "Look ahead:"))
        self.label_22.setText(_translate("generalizer", "Level:"))
        self.label_23.setText(_translate("generalizer", "Weight:"))
        self.label_2.setText(_translate("generalizer", "Threshold:"))
        self.label_4.setText(_translate("generalizer", "Thightness:"))
        self.label_24.setText(_translate("generalizer", "Slide:"))
        self.label_25.setText(_translate("generalizer", "Look ahead:"))
        self.label_26.setText(_translate("generalizer", "Slide:"))
        self.label_27.setText(_translate("generalizer", "Look ahead:"))
        self.label_9.setText(_translate("generalizer", "Alpha:"))
        self.label_10.setText(_translate("generalizer", "Beta:"))
        self.bBrowse.setText(_translate("generalizer", "Browse"))
        self.cbOutFile.setText(_translate("generalizer", "Save output layer"))
        item = self.tblBatchAlg.horizontalHeaderItem(0)
        item.setText(_translate("generalizer", "Algorithm"))
        item = self.tblBatchAlg.horizontalHeaderItem(1)
        item.setText(_translate("generalizer", "Parameter 1"))
        item = self.tblBatchAlg.horizontalHeaderItem(2)
        item.setText(_translate("generalizer", "Parameter 2"))
        self.bAddAlg.setText(_translate("generalizer", "Add"))
        self.bDelAlg.setText(_translate("generalizer", "Delete"))
        self.bEditAlg.setText(_translate("generalizer", "Edit"))
        self.bBrowseDir.setText(_translate("generalizer", "Browse"))
        self.cbOutDir.setText(_translate("generalizer", "Save output layer(s) to folder"))
        self.label_5.setText(_translate("generalizer", "Algorithm(s)"))
        self.label_6.setText(_translate("generalizer", "Choose layer(s)"))
