# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Documents and Settings\Pocisk\.qgis\python\plugins\generalizer\ui_generalizer.ui'
#
# Created: Mon Aug 29 17:54:54 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_generalizer(object):
    def setupUi(self, generalizer):
        generalizer.setObjectName(_fromUtf8("generalizer"))
        generalizer.resize(466, 263)
        self.gridLayout_2 = QtGui.QGridLayout(generalizer)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(generalizer)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.cbInput = QtGui.QComboBox(generalizer)
        self.cbInput.setObjectName(_fromUtf8("cbInput"))
        self.gridLayout_2.addWidget(self.cbInput, 1, 0, 1, 4)
        self.groupBox = QtGui.QGroupBox(generalizer)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.cbAlgorithm = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbAlgorithm.sizePolicy().hasHeightForWidth())
        self.cbAlgorithm.setSizePolicy(sizePolicy)
        self.cbAlgorithm.setObjectName(_fromUtf8("cbAlgorithm"))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cbAlgorithm, 0, 1, 1, 1)
        self.stackOptions = QtGui.QStackedWidget(self.groupBox)
        self.stackOptions.setObjectName(_fromUtf8("stackOptions"))
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_11 = QtGui.QLabel(self.page_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_8.addWidget(self.label_11, 0, 0, 1, 1)
        self.sbRemove_thresh = QtGui.QDoubleSpinBox(self.page_3)
        self.sbRemove_thresh.setDecimals(4)
        self.sbRemove_thresh.setMinimum(0.0001)
        self.sbRemove_thresh.setMaximum(99999999.0)
        self.sbRemove_thresh.setProperty(_fromUtf8("value"), 0.0001)
        self.sbRemove_thresh.setObjectName(_fromUtf8("sbRemove_thresh"))
        self.gridLayout_8.addWidget(self.sbRemove_thresh, 0, 1, 1, 1)
        self.stackOptions.addWidget(self.page_3)
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.gridLayout_9 = QtGui.QGridLayout(self.page_7)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_15 = QtGui.QLabel(self.page_7)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_9.addWidget(self.label_15, 0, 0, 1, 1)
        self.sbDP_thresh = QtGui.QDoubleSpinBox(self.page_7)
        self.sbDP_thresh.setDecimals(4)
        self.sbDP_thresh.setMinimum(0.0001)
        self.sbDP_thresh.setMaximum(99999999.0)
        self.sbDP_thresh.setProperty(_fromUtf8("value"), 0.0001)
        self.sbDP_thresh.setObjectName(_fromUtf8("sbDP_thresh"))
        self.gridLayout_9.addWidget(self.sbDP_thresh, 0, 1, 1, 1)
        self.stackOptions.addWidget(self.page_7)
        self.page_8 = QtGui.QWidget()
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.gridLayout_7 = QtGui.QGridLayout(self.page_8)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_10 = QtGui.QLabel(self.page_8)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_7.addWidget(self.label_10, 0, 0, 1, 1)
        self.sbLang_thresh = QtGui.QDoubleSpinBox(self.page_8)
        self.sbLang_thresh.setDecimals(4)
        self.sbLang_thresh.setMinimum(0.0001)
        self.sbLang_thresh.setMaximum(99999999.0)
        self.sbLang_thresh.setProperty(_fromUtf8("value"), 0.0001)
        self.sbLang_thresh.setObjectName(_fromUtf8("sbLang_thresh"))
        self.gridLayout_7.addWidget(self.sbLang_thresh, 0, 1, 2, 1)
        self.label_16 = QtGui.QLabel(self.page_8)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_7.addWidget(self.label_16, 1, 0, 2, 1)
        self.sbLang_LA = QtGui.QSpinBox(self.page_8)
        self.sbLang_LA.setMinimum(1)
        self.sbLang_LA.setMaximum(99999999)
        self.sbLang_LA.setProperty(_fromUtf8("value"), 1)
        self.sbLang_LA.setObjectName(_fromUtf8("sbLang_LA"))
        self.gridLayout_7.addWidget(self.sbLang_LA, 2, 1, 1, 1)
        self.stackOptions.addWidget(self.page_8)
        self.page_9 = QtGui.QWidget()
        self.page_9.setObjectName(_fromUtf8("page_9"))
        self.gridLayout_10 = QtGui.QGridLayout(self.page_9)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_17 = QtGui.QLabel(self.page_9)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_10.addWidget(self.label_17, 0, 0, 1, 1)
        self.sbReduction_thresh = QtGui.QDoubleSpinBox(self.page_9)
        self.sbReduction_thresh.setDecimals(4)
        self.sbReduction_thresh.setMinimum(0.0001)
        self.sbReduction_thresh.setMaximum(99999999.0)
        self.sbReduction_thresh.setObjectName(_fromUtf8("sbReduction_thresh"))
        self.gridLayout_10.addWidget(self.sbReduction_thresh, 0, 1, 1, 1)
        self.stackOptions.addWidget(self.page_9)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.sbBoyle_LA = QtGui.QSpinBox(self.page)
        self.sbBoyle_LA.setMinimum(2)
        self.sbBoyle_LA.setMaximum(99999999)
        self.sbBoyle_LA.setProperty(_fromUtf8("value"), 7)
        self.sbBoyle_LA.setObjectName(_fromUtf8("sbBoyle_LA"))
        self.gridLayout_3.addWidget(self.sbBoyle_LA, 0, 1, 1, 1)
        self.stackOptions.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_9 = QtGui.QLabel(self.page_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 0, 0, 1, 1)
        self.sbChaiken_level = QtGui.QSpinBox(self.page_2)
        self.sbChaiken_level.setMinimum(1)
        self.sbChaiken_level.setMaximum(99999)
        self.sbChaiken_level.setObjectName(_fromUtf8("sbChaiken_level"))
        self.gridLayout_6.addWidget(self.sbChaiken_level, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.page_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_6.addWidget(self.label_14, 1, 0, 1, 1)
        self.sbChaiken_weight = QtGui.QDoubleSpinBox(self.page_2)
        self.sbChaiken_weight.setProperty(_fromUtf8("value"), 3.0)
        self.sbChaiken_weight.setObjectName(_fromUtf8("sbChaiken_weight"))
        self.gridLayout_6.addWidget(self.sbChaiken_weight, 1, 1, 1, 1)
        self.stackOptions.addWidget(self.page_2)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_8 = QtGui.QLabel(self.page_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.sbDist_slide = QtGui.QDoubleSpinBox(self.page_4)
        self.sbDist_slide.setSingleStep(0.1)
        self.sbDist_slide.setProperty(_fromUtf8("value"), 0.5)
        self.sbDist_slide.setObjectName(_fromUtf8("sbDist_slide"))
        self.gridLayout_5.addWidget(self.sbDist_slide, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.page_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.sbDist_LA = QtGui.QSpinBox(self.page_4)
        self.sbDist_LA.setMinimum(3)
        self.sbDist_LA.setMaximum(999999)
        self.sbDist_LA.setSingleStep(2)
        self.sbDist_LA.setProperty(_fromUtf8("value"), 7)
        self.sbDist_LA.setObjectName(_fromUtf8("sbDist_LA"))
        self.gridLayout_5.addWidget(self.sbDist_LA, 1, 1, 1, 1)
        self.stackOptions.addWidget(self.page_4)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_5 = QtGui.QLabel(self.page_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.sbSlide_slide = QtGui.QDoubleSpinBox(self.page_5)
        self.sbSlide_slide.setSingleStep(0.1)
        self.sbSlide_slide.setProperty(_fromUtf8("value"), 0.5)
        self.sbSlide_slide.setObjectName(_fromUtf8("sbSlide_slide"))
        self.gridLayout_4.addWidget(self.sbSlide_slide, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.page_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.sbSlide_LA = QtGui.QSpinBox(self.page_5)
        self.sbSlide_LA.setMinimum(3)
        self.sbSlide_LA.setMaximum(99999)
        self.sbSlide_LA.setSingleStep(2)
        self.sbSlide_LA.setProperty(_fromUtf8("value"), 7)
        self.sbSlide_LA.setObjectName(_fromUtf8("sbSlide_LA"))
        self.gridLayout_4.addWidget(self.sbSlide_LA, 1, 1, 1, 1)
        self.stackOptions.addWidget(self.page_5)
        self.gridLayout.addWidget(self.stackOptions, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 4)
        self.label_3 = QtGui.QLabel(generalizer)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.eOutput = QtGui.QLineEdit(generalizer)
        self.eOutput.setObjectName(_fromUtf8("eOutput"))
        self.gridLayout_2.addWidget(self.eOutput, 4, 0, 1, 3)
        self.bBrowse = QtGui.QPushButton(generalizer)
        self.bBrowse.setObjectName(_fromUtf8("bBrowse"))
        self.gridLayout_2.addWidget(self.bBrowse, 4, 3, 1, 1)
        self.bCancel = QtGui.QPushButton(generalizer)
        self.bCancel.setObjectName(_fromUtf8("bCancel"))
        self.gridLayout_2.addWidget(self.bCancel, 5, 3, 1, 1)
        self.bOk = QtGui.QPushButton(generalizer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bOk.sizePolicy().hasHeightForWidth())
        self.bOk.setSizePolicy(sizePolicy)
        self.bOk.setObjectName(_fromUtf8("bOk"))
        self.gridLayout_2.addWidget(self.bOk, 5, 2, 1, 1)
        self.bHelp = QtGui.QPushButton(generalizer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bHelp.sizePolicy().hasHeightForWidth())
        self.bHelp.setSizePolicy(sizePolicy)
        self.bHelp.setFlat(True)
        self.bHelp.setObjectName(_fromUtf8("bHelp"))
        self.gridLayout_2.addWidget(self.bHelp, 0, 3, 1, 1)

        self.retranslateUi(generalizer)
        self.cbAlgorithm.setCurrentIndex(1)
        self.stackOptions.setCurrentIndex(0)
        QtCore.QObject.connect(self.bCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), generalizer.close)
        QtCore.QMetaObject.connectSlotsByName(generalizer)

    def retranslateUi(self, generalizer):
        generalizer.setWindowTitle(QtGui.QApplication.translate("generalizer", "Generalizer", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("generalizer", "Input line layer:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("generalizer", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("generalizer", "Alghoritm:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(0, QtGui.QApplication.translate("generalizer", "-----Generalizing-----", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(1, QtGui.QApplication.translate("generalizer", "Remove small objects", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(2, QtGui.QApplication.translate("generalizer", "-----Simplifying-----", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(3, QtGui.QApplication.translate("generalizer", "Douglas-Peucker Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(4, QtGui.QApplication.translate("generalizer", "Lang Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(5, QtGui.QApplication.translate("generalizer", "Vertex Reduction", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(6, QtGui.QApplication.translate("generalizer", "-----Smoothing-----", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(7, QtGui.QApplication.translate("generalizer", "Boyle\'s Forward-Looking Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(8, QtGui.QApplication.translate("generalizer", "Chaiken\'s Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(9, QtGui.QApplication.translate("generalizer", "McMaster\'s Distance-Weighting Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(10, QtGui.QApplication.translate("generalizer", "McMaster\'s Sliding Averaging Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("generalizer", "Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("generalizer", "Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("generalizer", "Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("generalizer", "Looka ahead:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("generalizer", "Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("generalizer", "Look ahead:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("generalizer", "Level:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("generalizer", "Weight:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("generalizer", "Slide:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("generalizer", "Look ahead:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("generalizer", "Slide:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("generalizer", "Look ahead:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("generalizer", "Output layer:", None, QtGui.QApplication.UnicodeUTF8))
        self.bBrowse.setText(QtGui.QApplication.translate("generalizer", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.bCancel.setText(QtGui.QApplication.translate("generalizer", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setText(QtGui.QApplication.translate("generalizer", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.bHelp.setText(QtGui.QApplication.translate("generalizer", "?", None, QtGui.QApplication.UnicodeUTF8))

