# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Documents and Settings\Pocisk\.qgis\python\plugins\generalizer\ui_generalizer.ui'
#
# Created: Sun Sep 11 16:43:56 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_generalizer(object):
    def setupUi(self, generalizer):
        generalizer.setObjectName(_fromUtf8("generalizer"))
        generalizer.resize(493, 348)
        self.gridLayout_20 = QtGui.QGridLayout(generalizer)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.cbBatch = QtGui.QCheckBox(generalizer)
        self.cbBatch.setObjectName(_fromUtf8("cbBatch"))
        self.gridLayout_20.addWidget(self.cbBatch, 0, 0, 1, 1)
        self.bHelp = QtGui.QPushButton(generalizer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bHelp.sizePolicy().hasHeightForWidth())
        self.bHelp.setSizePolicy(sizePolicy)
        self.bHelp.setFlat(True)
        self.bHelp.setObjectName(_fromUtf8("bHelp"))
        self.gridLayout_20.addWidget(self.bHelp, 0, 2, 1, 1)
        self.bOk = QtGui.QPushButton(generalizer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bOk.sizePolicy().hasHeightForWidth())
        self.bOk.setSizePolicy(sizePolicy)
        self.bOk.setObjectName(_fromUtf8("bOk"))
        self.gridLayout_20.addWidget(self.bOk, 2, 1, 1, 1)
        self.bCancel = QtGui.QPushButton(generalizer)
        self.bCancel.setObjectName(_fromUtf8("bCancel"))
        self.gridLayout_20.addWidget(self.bCancel, 2, 2, 1, 1)
        self.stackBatch = QtGui.QStackedWidget(generalizer)
        self.stackBatch.setObjectName(_fromUtf8("stackBatch"))
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.gridLayout_19 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.label = QtGui.QLabel(self.page_6)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_19.addWidget(self.label, 0, 0, 1, 1)
        self.cbInput = QtGui.QComboBox(self.page_6)
        self.cbInput.setObjectName(_fromUtf8("cbInput"))
        self.gridLayout_19.addWidget(self.cbInput, 1, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(self.page_6)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.cbAlgorithm = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbAlgorithm.sizePolicy().hasHeightForWidth())
        self.cbAlgorithm.setSizePolicy(sizePolicy)
        self.cbAlgorithm.setObjectName(_fromUtf8("cbAlgorithm"))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.cbAlgorithm.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cbAlgorithm, 0, 1, 1, 1)
        self.stackOptions = QtGui.QStackedWidget(self.groupBox)
        self.stackOptions.setObjectName(_fromUtf8("stackOptions"))
        self.page_11 = QtGui.QWidget()
        self.page_11.setObjectName(_fromUtf8("page_11"))
        self.gridLayout_11 = QtGui.QGridLayout(self.page_11)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_12 = QtGui.QLabel(self.page_11)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_11.addWidget(self.label_12, 0, 0, 1, 1)
        self.sbRemove_thresh = QtGui.QDoubleSpinBox(self.page_11)
        self.sbRemove_thresh.setDecimals(4)
        self.sbRemove_thresh.setMinimum(0.0001)
        self.sbRemove_thresh.setMaximum(9999999.9999)
        self.sbRemove_thresh.setProperty(_fromUtf8("value"), 0.0001)
        self.sbRemove_thresh.setObjectName(_fromUtf8("sbRemove_thresh"))
        self.gridLayout_11.addWidget(self.sbRemove_thresh, 0, 1, 1, 1)
        self.stackOptions.addWidget(self.page_11)
        self.page_12 = QtGui.QWidget()
        self.page_12.setObjectName(_fromUtf8("page_12"))
        self.gridLayout_12 = QtGui.QGridLayout(self.page_12)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_18 = QtGui.QLabel(self.page_12)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_12.addWidget(self.label_18, 0, 0, 1, 1)
        self.sbDP_thresh = QtGui.QDoubleSpinBox(self.page_12)
        self.sbDP_thresh.setDecimals(4)
        self.sbDP_thresh.setMinimum(0.0001)
        self.sbDP_thresh.setMaximum(9999999.9999)
        self.sbDP_thresh.setProperty(_fromUtf8("value"), 0.0001)
        self.sbDP_thresh.setObjectName(_fromUtf8("sbDP_thresh"))
        self.gridLayout_12.addWidget(self.sbDP_thresh, 0, 1, 1, 1)
        self.stackOptions.addWidget(self.page_12)
        self.page_13 = QtGui.QWidget()
        self.page_13.setObjectName(_fromUtf8("page_13"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page_13)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_13 = QtGui.QLabel(self.page_13)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.sbLang_thresh = QtGui.QDoubleSpinBox(self.page_13)
        self.sbLang_thresh.setDecimals(4)
        self.sbLang_thresh.setMinimum(0.0001)
        self.sbLang_thresh.setMaximum(9999999.9999)
        self.sbLang_thresh.setProperty(_fromUtf8("value"), 0.0001)
        self.sbLang_thresh.setObjectName(_fromUtf8("sbLang_thresh"))
        self.gridLayout_3.addWidget(self.sbLang_thresh, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.page_13)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 1, 0, 1, 1)
        self.sbLang_LA = QtGui.QSpinBox(self.page_13)
        self.sbLang_LA.setMinimum(1)
        self.sbLang_LA.setMaximum(9999)
        self.sbLang_LA.setProperty(_fromUtf8("value"), 8)
        self.sbLang_LA.setObjectName(_fromUtf8("sbLang_LA"))
        self.gridLayout_3.addWidget(self.sbLang_LA, 1, 1, 1, 1)
        self.stackOptions.addWidget(self.page_13)
        self.page_14 = QtGui.QWidget()
        self.page_14.setObjectName(_fromUtf8("page_14"))
        self.gridLayout_14 = QtGui.QGridLayout(self.page_14)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_20 = QtGui.QLabel(self.page_14)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_14.addWidget(self.label_20, 0, 0, 1, 1)
        self.sbReduction_thresh = QtGui.QDoubleSpinBox(self.page_14)
        self.sbReduction_thresh.setDecimals(4)
        self.sbReduction_thresh.setMinimum(0.0001)
        self.sbReduction_thresh.setMaximum(9999999.9999)
        self.sbReduction_thresh.setObjectName(_fromUtf8("sbReduction_thresh"))
        self.gridLayout_14.addWidget(self.sbReduction_thresh, 0, 1, 1, 1)
        self.stackOptions.addWidget(self.page_14)
        self.page_15 = QtGui.QWidget()
        self.page_15.setObjectName(_fromUtf8("page_15"))
        self.gridLayout_15 = QtGui.QGridLayout(self.page_15)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.label_21 = QtGui.QLabel(self.page_15)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_15.addWidget(self.label_21, 0, 0, 1, 1)
        self.sbBoyle_LA = QtGui.QSpinBox(self.page_15)
        self.sbBoyle_LA.setMinimum(2)
        self.sbBoyle_LA.setMaximum(999)
        self.sbBoyle_LA.setProperty(_fromUtf8("value"), 7)
        self.sbBoyle_LA.setObjectName(_fromUtf8("sbBoyle_LA"))
        self.gridLayout_15.addWidget(self.sbBoyle_LA, 0, 1, 1, 1)
        self.stackOptions.addWidget(self.page_15)
        self.page_16 = QtGui.QWidget()
        self.page_16.setObjectName(_fromUtf8("page_16"))
        self.gridLayout_16 = QtGui.QGridLayout(self.page_16)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_22 = QtGui.QLabel(self.page_16)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_16.addWidget(self.label_22, 0, 0, 1, 1)
        self.sbChaiken_level = QtGui.QSpinBox(self.page_16)
        self.sbChaiken_level.setMinimum(1)
        self.sbChaiken_level.setMaximum(99)
        self.sbChaiken_level.setObjectName(_fromUtf8("sbChaiken_level"))
        self.gridLayout_16.addWidget(self.sbChaiken_level, 0, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.page_16)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_16.addWidget(self.label_23, 1, 0, 1, 1)
        self.sbChaiken_weight = QtGui.QDoubleSpinBox(self.page_16)
        self.sbChaiken_weight.setMinimum(1.0)
        self.sbChaiken_weight.setProperty(_fromUtf8("value"), 3.0)
        self.sbChaiken_weight.setObjectName(_fromUtf8("sbChaiken_weight"))
        self.gridLayout_16.addWidget(self.sbChaiken_weight, 1, 1, 1, 1)
        self.stackOptions.addWidget(self.page_16)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout = QtGui.QGridLayout(self.page)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.sbHermite_tightness = QtGui.QDoubleSpinBox(self.page)
        self.sbHermite_tightness.setProperty(_fromUtf8("value"), 0.5)
        self.sbHermite_tightness.setObjectName(_fromUtf8("sbHermite_tightness"))
        self.gridLayout.addWidget(self.sbHermite_tightness, 1, 1, 1, 1)
        self.sbHermite_steps = QtGui.QDoubleSpinBox(self.page)
        self.sbHermite_steps.setDecimals(4)
        self.sbHermite_steps.setMaximum(9999999.9999)
        self.sbHermite_steps.setProperty(_fromUtf8("value"), 0.0001)
        self.sbHermite_steps.setObjectName(_fromUtf8("sbHermite_steps"))
        self.gridLayout.addWidget(self.sbHermite_steps, 0, 1, 1, 1)
        self.stackOptions.addWidget(self.page)
        self.page_17 = QtGui.QWidget()
        self.page_17.setObjectName(_fromUtf8("page_17"))
        self.gridLayout_17 = QtGui.QGridLayout(self.page_17)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.label_24 = QtGui.QLabel(self.page_17)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_17.addWidget(self.label_24, 0, 0, 1, 1)
        self.sbDist_slide = QtGui.QDoubleSpinBox(self.page_17)
        self.sbDist_slide.setSingleStep(0.1)
        self.sbDist_slide.setProperty(_fromUtf8("value"), 0.5)
        self.sbDist_slide.setObjectName(_fromUtf8("sbDist_slide"))
        self.gridLayout_17.addWidget(self.sbDist_slide, 0, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.page_17)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_17.addWidget(self.label_25, 1, 0, 1, 1)
        self.sbDist_LA = QtGui.QSpinBox(self.page_17)
        self.sbDist_LA.setMinimum(3)
        self.sbDist_LA.setMaximum(999)
        self.sbDist_LA.setSingleStep(2)
        self.sbDist_LA.setProperty(_fromUtf8("value"), 7)
        self.sbDist_LA.setObjectName(_fromUtf8("sbDist_LA"))
        self.gridLayout_17.addWidget(self.sbDist_LA, 1, 1, 1, 1)
        self.stackOptions.addWidget(self.page_17)
        self.page_18 = QtGui.QWidget()
        self.page_18.setObjectName(_fromUtf8("page_18"))
        self.gridLayout_18 = QtGui.QGridLayout(self.page_18)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.label_26 = QtGui.QLabel(self.page_18)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_18.addWidget(self.label_26, 0, 0, 1, 1)
        self.sbSlide_slide = QtGui.QDoubleSpinBox(self.page_18)
        self.sbSlide_slide.setSingleStep(0.1)
        self.sbSlide_slide.setProperty(_fromUtf8("value"), 0.5)
        self.sbSlide_slide.setObjectName(_fromUtf8("sbSlide_slide"))
        self.gridLayout_18.addWidget(self.sbSlide_slide, 0, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.page_18)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_18.addWidget(self.label_27, 1, 0, 1, 1)
        self.sbSlide_LA = QtGui.QSpinBox(self.page_18)
        self.sbSlide_LA.setMinimum(3)
        self.sbSlide_LA.setMaximum(999)
        self.sbSlide_LA.setSingleStep(2)
        self.sbSlide_LA.setProperty(_fromUtf8("value"), 7)
        self.sbSlide_LA.setObjectName(_fromUtf8("sbSlide_LA"))
        self.gridLayout_18.addWidget(self.sbSlide_LA, 1, 1, 1, 1)
        self.stackOptions.addWidget(self.page_18)
        self.gridLayout_2.addWidget(self.stackOptions, 1, 0, 1, 2)
        self.gridLayout_19.addWidget(self.groupBox, 2, 0, 1, 2)
        self.eOutput = QtGui.QLineEdit(self.page_6)
        self.eOutput.setEnabled(False)
        self.eOutput.setObjectName(_fromUtf8("eOutput"))
        self.gridLayout_19.addWidget(self.eOutput, 4, 0, 1, 1)
        self.bBrowse = QtGui.QPushButton(self.page_6)
        self.bBrowse.setEnabled(False)
        self.bBrowse.setObjectName(_fromUtf8("bBrowse"))
        self.gridLayout_19.addWidget(self.bBrowse, 4, 1, 1, 1)
        self.cbOutFile = QtGui.QCheckBox(self.page_6)
        self.cbOutFile.setObjectName(_fromUtf8("cbOutFile"))
        self.gridLayout_19.addWidget(self.cbOutFile, 3, 0, 1, 1)
        self.stackBatch.addWidget(self.page_6)
        self.page_10 = QtGui.QWidget()
        self.page_10.setObjectName(_fromUtf8("page_10"))
        self.gridLayout_21 = QtGui.QGridLayout(self.page_10)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.lstLayers = QtGui.QListWidget(self.page_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstLayers.sizePolicy().hasHeightForWidth())
        self.lstLayers.setSizePolicy(sizePolicy)
        self.lstLayers.setObjectName(_fromUtf8("lstLayers"))
        self.gridLayout_21.addWidget(self.lstLayers, 1, 0, 1, 1)
        self.tblBatchAlg = QtGui.QTableWidget(self.page_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblBatchAlg.sizePolicy().hasHeightForWidth())
        self.tblBatchAlg.setSizePolicy(sizePolicy)
        self.tblBatchAlg.setObjectName(_fromUtf8("tblBatchAlg"))
        self.tblBatchAlg.setColumnCount(3)
        self.tblBatchAlg.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblBatchAlg.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblBatchAlg.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblBatchAlg.setHorizontalHeaderItem(2, item)
        self.gridLayout_21.addWidget(self.tblBatchAlg, 3, 0, 3, 1)
        self.bAddAlg = QtGui.QPushButton(self.page_10)
        self.bAddAlg.setObjectName(_fromUtf8("bAddAlg"))
        self.gridLayout_21.addWidget(self.bAddAlg, 3, 1, 1, 1)
        self.bDelAlg = QtGui.QPushButton(self.page_10)
        self.bDelAlg.setObjectName(_fromUtf8("bDelAlg"))
        self.gridLayout_21.addWidget(self.bDelAlg, 4, 1, 1, 1)
        self.bEditAlg = QtGui.QPushButton(self.page_10)
        self.bEditAlg.setObjectName(_fromUtf8("bEditAlg"))
        self.gridLayout_21.addWidget(self.bEditAlg, 5, 1, 1, 1)
        self.eDir = QtGui.QLineEdit(self.page_10)
        self.eDir.setEnabled(False)
        self.eDir.setObjectName(_fromUtf8("eDir"))
        self.gridLayout_21.addWidget(self.eDir, 7, 0, 1, 1)
        self.bBrowseDir = QtGui.QPushButton(self.page_10)
        self.bBrowseDir.setEnabled(False)
        self.bBrowseDir.setObjectName(_fromUtf8("bBrowseDir"))
        self.gridLayout_21.addWidget(self.bBrowseDir, 7, 1, 1, 1)
        self.cbOutDir = QtGui.QCheckBox(self.page_10)
        self.cbOutDir.setObjectName(_fromUtf8("cbOutDir"))
        self.gridLayout_21.addWidget(self.cbOutDir, 6, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.page_10)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_21.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.page_10)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_21.addWidget(self.label_6, 0, 0, 1, 1)
        self.stackBatch.addWidget(self.page_10)
        self.gridLayout_20.addWidget(self.stackBatch, 1, 0, 1, 3)
        self.label.setBuddy(self.cbInput)
        self.label_12.setBuddy(self.sbRemove_thresh)

        self.retranslateUi(generalizer)
        self.stackBatch.setCurrentIndex(0)
        self.cbAlgorithm.setCurrentIndex(1)
        self.stackOptions.setCurrentIndex(0)
        QtCore.QObject.connect(self.bCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), generalizer.close)
        QtCore.QMetaObject.connectSlotsByName(generalizer)
        generalizer.setTabOrder(self.cbBatch, self.cbInput)
        generalizer.setTabOrder(self.cbInput, self.cbAlgorithm)
        generalizer.setTabOrder(self.cbAlgorithm, self.sbRemove_thresh)
        generalizer.setTabOrder(self.sbRemove_thresh, self.cbOutFile)
        generalizer.setTabOrder(self.cbOutFile, self.eOutput)
        generalizer.setTabOrder(self.eOutput, self.bBrowse)
        generalizer.setTabOrder(self.bBrowse, self.bOk)
        generalizer.setTabOrder(self.bOk, self.bCancel)
        generalizer.setTabOrder(self.bCancel, self.sbLang_LA)
        generalizer.setTabOrder(self.sbLang_LA, self.sbReduction_thresh)
        generalizer.setTabOrder(self.sbReduction_thresh, self.sbBoyle_LA)
        generalizer.setTabOrder(self.sbBoyle_LA, self.sbChaiken_level)
        generalizer.setTabOrder(self.sbChaiken_level, self.sbChaiken_weight)
        generalizer.setTabOrder(self.sbChaiken_weight, self.sbHermite_steps)
        generalizer.setTabOrder(self.sbHermite_steps, self.sbHermite_tightness)
        generalizer.setTabOrder(self.sbHermite_tightness, self.sbDist_slide)
        generalizer.setTabOrder(self.sbDist_slide, self.sbDist_LA)
        generalizer.setTabOrder(self.sbDist_LA, self.sbSlide_slide)
        generalizer.setTabOrder(self.sbSlide_slide, self.sbSlide_LA)
        generalizer.setTabOrder(self.sbSlide_LA, self.bHelp)
        generalizer.setTabOrder(self.bHelp, self.sbLang_thresh)
        generalizer.setTabOrder(self.sbLang_thresh, self.sbDP_thresh)
        generalizer.setTabOrder(self.sbDP_thresh, self.lstLayers)
        generalizer.setTabOrder(self.lstLayers, self.tblBatchAlg)
        generalizer.setTabOrder(self.tblBatchAlg, self.bAddAlg)
        generalizer.setTabOrder(self.bAddAlg, self.bDelAlg)
        generalizer.setTabOrder(self.bDelAlg, self.bEditAlg)
        generalizer.setTabOrder(self.bEditAlg, self.eDir)
        generalizer.setTabOrder(self.eDir, self.bBrowseDir)
        generalizer.setTabOrder(self.bBrowseDir, self.cbOutDir)

    def retranslateUi(self, generalizer):
        generalizer.setWindowTitle(QtGui.QApplication.translate("generalizer", "Generalizer", None, QtGui.QApplication.UnicodeUTF8))
        self.cbBatch.setText(QtGui.QApplication.translate("generalizer", "Batch mode", None, QtGui.QApplication.UnicodeUTF8))
        self.bHelp.setText(QtGui.QApplication.translate("generalizer", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.bOk.setText(QtGui.QApplication.translate("generalizer", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.bCancel.setText(QtGui.QApplication.translate("generalizer", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("generalizer", "Input line layer:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("generalizer", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("generalizer", "Alghoritm:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(0, QtGui.QApplication.translate("generalizer", "-----Generalizing-----", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(1, QtGui.QApplication.translate("generalizer", "Remove small objects", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(2, QtGui.QApplication.translate("generalizer", "-----Simplifying-----", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(3, QtGui.QApplication.translate("generalizer", "Douglas-Peucker Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(4, QtGui.QApplication.translate("generalizer", "Lang Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(5, QtGui.QApplication.translate("generalizer", "Vertex Reduction", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(6, QtGui.QApplication.translate("generalizer", "-----Smoothing-----", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(7, QtGui.QApplication.translate("generalizer", "Boyle\'s Forward-Looking Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(8, QtGui.QApplication.translate("generalizer", "Chaiken\'s Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(9, QtGui.QApplication.translate("generalizer", "Hermite Spline Interpolation", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(10, QtGui.QApplication.translate("generalizer", "McMaster\'s Distance-Weighting Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.cbAlgorithm.setItemText(11, QtGui.QApplication.translate("generalizer", "McMaster\'s Sliding Averaging Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("generalizer", "Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("generalizer", "Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("generalizer", "Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("generalizer", "Looka ahead:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("generalizer", "Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("generalizer", "Look ahead:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("generalizer", "Level:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("generalizer", "Weight:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("generalizer", "Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("generalizer", "Thightness:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("generalizer", "Slide:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("generalizer", "Look ahead:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("generalizer", "Slide:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("generalizer", "Look ahead:", None, QtGui.QApplication.UnicodeUTF8))
        self.bBrowse.setText(QtGui.QApplication.translate("generalizer", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.cbOutFile.setText(QtGui.QApplication.translate("generalizer", "Save output layer", None, QtGui.QApplication.UnicodeUTF8))
        self.tblBatchAlg.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("generalizer", "Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.tblBatchAlg.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("generalizer", "Parameter 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tblBatchAlg.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("generalizer", "Parameter 2", None, QtGui.QApplication.UnicodeUTF8))
        self.bAddAlg.setText(QtGui.QApplication.translate("generalizer", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.bDelAlg.setText(QtGui.QApplication.translate("generalizer", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.bEditAlg.setText(QtGui.QApplication.translate("generalizer", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.bBrowseDir.setText(QtGui.QApplication.translate("generalizer", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.cbOutDir.setText(QtGui.QApplication.translate("generalizer", "Save output layer(s) to folder", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("generalizer", "Algorithm(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("generalizer", "Choose layer(s)", None, QtGui.QApplication.UnicodeUTF8))

